var settings = {
  "targetSuccess": "$user has set the $currency pool target to $target $currency",
  "CorePermission": "everyone",
  "goalExample": "!command goal A brand new car",
  "goalClear": false,
  "removeModeratorOnly": true,
  "CoreCommand": "!pool",
  "CoreEnabled": true,
  "targetCooldown": 4.0,
  "targetExample": "!command target 11",
  "transferEnabled": true,
  "commitEnabled": true,
  "targetEnabled": true,
  "targetAliases": "",
  "removePermission": "everyone",
  "topExample": "!command top 11",
  "topCooldown": 4.0,
  "removeSelfFailure": "Sorry, $user, but you cannot refund $contribution $currency. You can refund a maximum of $total_contribution $currency",
  "removeOtherFailure": "Sorry, $user, but you cannot refund $contribution $currency to $target. You can refund a maximum of $total_contribution $currency",
  "removeCooldown": 4.0,
  "targetPermission": "editor",
  "goalEnabled": true,
  "commitExample": "!command commit",
  "addSuccess": "Thank you, $user, for adding $contribution $currency to the pot. You've added $total_contribution $currency so far.",
  "OverlayStyle": "donation-goal",
  "addEnabled": true,
  "transferAliases": "",
  "commitSuccess": "$user has committed and reset the currency pool.",
  "removeOtherSuccess": "$user has refunded $contribution $currency to $target",
  "goalCooldown": 4.0,
  "addExample": "!command add 123",
  "addGenerous": false,
  "removeAliases": "withdraw,subtract,sub,undo,refund",
  "topAliases": "leaders,leaderboard",
  "commitConfirmation": "Are you sure you wish to reset the goal? Use this command again to confirm.",
  "commitAliases": "clear,reset",
  "addCooldown": 1.0,
  "transferMessage": "$user transferred $from's $currency in the pool to $to",
  "removeEnabled": true,
  "transferCooldown": 4.0,
  "commitCooldown": 4.0,
  "removeSelfSuccess": "$user has been refunded $contribution $currency",
  "topEnabled": true,
  "topPermission": "everyone",
  "topDefault": 3.0,
  "goalPermission": "editor",
  "commitPermission": "editor",
  "goalSuccess": "$user set the $currency donation goal to \"$goal\"",
  "transferExample": "!command transfer Viewer1 Viewer2",
  "removeExample": "!command remove 123, !command remove otheruser 123",
  "addPermission": "everyone",
  "transferPermission": "editor",
  "CoreCooldown": 1.0,
  "CoreMessage": "$total $currency have been donated towards \"$goal\". $remaining $currency remaining to reach the goal.",
  "addAliases": "deposit,spend,donate,contribute",
  "addGenerousMessage": "Thank you for your generosity, $user, but the goal has already been reached.",
  "goalAliases": "",
  "addFailure": "Sorry, $user. You only have $currency_available $currency available, so you cannot contribute $contribution $currency.",
  "topMessage": "Top $currency contributors: $top",
  "OverlayApiToken": ""
};